### ISSUE TITLE
How to run with CARLA

### ISSUE THREAD

**Issue by rsuwa** [baimingc/delay-aware-MARL#1]
In the first edition of your [paper](<https://arxiv.org/pdf/2005.05441v1.pdf>) you used CARLA to simulate unsignalized intersections and parking, how can we replicate this?
I would like to know if you have any CARLA codes that you used for your experiments.

**Comment by baimingc** [comment]
As you noticed, we have switched to a simplified simulator from CARLA for faster running speed and stability. We will not provide the codes for the older version. In fact, the only different part is setting up the environments in CARLA and defining the gym-style functions like _reset()_ and _step()_, which is very flexible. You can find many good tutorials for this online if interested, for example [here](https://pythonprogramming.net/reinforcement-learning-self-driving-autonomous-cars-carla-python/).

**Comment by rsuwa** [comment]
@baimingc 
Thanks for the advice. I'll give it a try.
By the way, Could you tell me the procedure for running [this](https://github.com/baimingc/highway_multiagent_env)?
I was able to get multiagent-particle-envs to work, but there is no description of how to get highway-multiagent-env to work, so I don't know how to reproduce it.

**Comment by baimingc** [comment]
@rsuwa 
Thanks for your interest. I've added a little bit more description in that repo. Basically you need to first install that environment, and then run `env = gym.make("intersection-multiagent-v0")` so that you can interact with it. Other parts (agent training) are almost the same as the provided codes here.

**Comment by rsuwa** [comment]
@baimingc 
Thank you for adding the explanation!
I'll try it out as soon as I can.
